repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.4
    hooks:
      - id: isort
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=80, --safe, --py36]
